# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=200)),
                ('callback_number', models.CharField(max_length=13)),
            ],
        ),
    ]
