# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160828_0223'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplestory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
        migrations.AddField(
            model_name='simplestory',
            name='snippet',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
