# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160828_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Country'),
        ),
    ]
