# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stories', '0004_auto_20160828_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplestory',
            old_name='primary_keyword',
            new_name='violence_type',
        ),
        migrations.RemoveField(
            model_name='simplestory',
            name='secondary_keyword',
        ),
        migrations.RemoveField(
            model_name='simplestory',
            name='tertiary_keyword',
        ),
        migrations.AddField(
            model_name='simplestory',
            name='additional_info',
            field=models.CharField(blank=True, choices=[('cust', 'Custody'), ('gr', 'Gang Rape')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simplestory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Author'),
        ),
        migrations.AddField(
            model_name='simplestory',
            name='result_type',
            field=models.CharField(blank=True, choices=[('J', 'Justice'), ('S', 'Safety'), ('F', 'Family/Custody')], max_length=200, null=True),
        ),
    ]
