# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
