# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_country_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='has_postcode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
    ]
