# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160828_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='emergency_number',
            field=models.IntegerField(default=911),
            preserve_default=False,
        ),
    ]
