# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_country_emergency_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
