# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20160828_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplestory',
            name='keywords',
        ),
        migrations.AddField(
            model_name='simplestory',
            name='primary_keyword',
            field=models.CharField(choices=[('D', 'domestic'), ('C', 'community')], default='D', max_length=200),
        ),
        migrations.AddField(
            model_name='simplestory',
            name='secondary_keyword',
            field=models.CharField(choices=[('J', 'Justice'), ('S', 'Safety'), ('F', 'Family/Custody')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simplestory',
            name='tertiary_keyword',
            field=models.CharField(choices=[('cust', 'Custody'), ('gr', 'gang rape')], max_length=200, null=True),
        ),
    ]
